name: Sync Files

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    - cron: 55 15 * * *

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: 准备完成
      uses: actions/checkout@v2

    - name: 下载架构编译配置文件
      run: |
        mkdir -p ./RK33
        wget -O  ./RK33/feeds.conf https://fw0.koolcenter.com/iStoreOS/r2s/feeds.conf
        wget -O  ./RK33/.config https://fw0.koolcenter.com/iStoreOS/r2s/config.buildinfo

        mkdir -p ./RK35
        wget -O ./RK35/feeds.conf https://fw0.koolcenter.com/iStoreOS/h88k/feeds.conf
        wget -O ./RK35/.config https://fw0.koolcenter.com/iStoreOS/h88k/config.buildinfo

        mkdir -p ./X86
        wget -O ./X86/feeds.conf https://fw0.koolcenter.com/iStoreOS/x86_64_efi/feeds.conf
        wget -O ./X86/.config https://fw0.koolcenter.com/iStoreOS/x86_64_efi/config.buildinfo

    - name: 同步配置
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: master
        publish_dir: ./
        user_name: 'GitHub Action'
        user_email: 'github-actions[bot]@github.com'
        exclude_assets: ''
        keep_files: true
        commit_message: "Sync files"
        enable_jekyll: true

    - name: 删除运行记录
      uses: Mattraks/delete-workflow-runs@main
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        retain_days: 0
        keep_minimum_runs: 1

    - name: 删除自动发布的旧固件
      uses: dev-drprasad/delete-older-releases@v0.1.0
      if: env.UPLOAD_RELEASE == 'true' && !cancelled()
      with:
        keep_latest: 2
        delete_tags: true
